#!/usr/bin/env bash
#
# https://github.com/vovanr/clone-my-repo
#
# Usage: clone-my-repo <string>

usage() {
    echo "Usage: $0 <string>" 1>&2;
    exit 1;
}

# Arguments exists
if [ -n "${1}" ];then
    dir=$(echo $HOME)"/work/"${1}

    # Exit if directory already exists
    if [ -d "$dir" ]; then
        echo -e "Error: Repository \""${1}"\" already exists"
        exit 2
        # Return 2
        # Exit Status: Incorrect usage
    else
        git clone git@github.com:VovanR/${1}.git ~/work/${1}
    fi
else
    # Print help
    usage
fi

# Debug
# echo -e "\n"
# echo -e "script:\t"$0
# echo -e "arguments.lenght:\t"$#
# echo -e "is previous running is successful ( 0 - successful ):\t"$?
# echo -e "PID:\t"$$
# echo -e "last PID:\t"$!
# echo -e "all arguments:\t"$*
# echo -e "all arguments2:\t"$@
# echo -e "last argument of last sh:\t"$_


echo -e "Successful execution"
exit 0
# Return 0
# Exit Status: Success
